In [13]:
import requests
from bs4 import BeautifulSoup
# 引用requests库
url = 'https://www.cp550.com/data/bjpk10/lotteryList/2019-01-02.json?KJXTURH3UD9JAVWD2RMH'
res_music = requests.get('https://www.cp550.com/data/bjpk10/lotteryList/2019-01-02.json?KJXTURH3UD9JAVWD2RMH')


# 调用get方法，下载这个字典
json_music = res_music.json()

# 使用json()方法，将response对象，转为列表/字典
#print(type(res_music.text))
#print(res_music.text)

<class 'str'>
[{"openDateTime":"2019-01-02 23:57:30","issue":"723663","openNum":[10,6,7,9,4,3,2,1,8,5],"sumArr":[16,2,1,0],"dtArr":[1,2,1,1,1],"formArr":[],"mimcryArr":[],"compareArr":[2,2,2,1,2,1,1,2,1,1],"sumType":null,"wuxing":null},{"openDateTime":"2019-01-02 23:52:30","issue":"723662","openNum":[1,9,4,5,2,7,3,6,10,8],"sumArr":[10,2,2,0],"dtArr":[2,2,2,1,2],"formArr":[],"mimcryArr":[],"compareArr":[1,1,2,1,1,2,2,2,1,2],"sumType":null,"wuxing":null},{"openDateTime":"2019-01-02 23:47:30","issue":"723661","openNum":[9,8,2,3,7,5,6,1,4,10],"sumArr":[17,1,1,0],"dtArr":[2,1,1,2,1],"formArr":[],"mimcryArr":[],"compareArr":[2,1,1,2,2,2,1,1,1,2],"sumType":null,"wuxing":null},{"openDateTime":"2019-01-02 23:42:30","issue":"723660","openNum":[3,1,5,9,10,6,2,4,8,7],"sumArr":[4,2,2,0],"dtArr":[2,2,1,1,1],"formArr":[],"mimcryArr":[],"compareArr":[1,2,1,2,1,2,2,2,1,1],"sumType":null,"wuxing":null},{"openDateTime":"2019-01-02 23:37:30","issue":"723659","openNum":[2,4,10,9,8,1,7,6,5,3],"sumArr":[6,2,

In [16]:
print(type(json_music[0]))

<class 'dict'>


In [23]:
print(chr(ord('A')+1))

B


In [20]:
import requests,openpyxl
wb=openpyxl.Workbook()  
#创建工作薄
sheet=wb.active 
#获取工作薄的活动表
sheet.title='openNum' 
data_len = len(json_music[0]['openNum'])
print(data_len)


10
[10, 6, 7, 9, 4, 3, 2, 1, 8, 5]
[1, 9, 4, 5, 2, 7, 3, 6, 10, 8]
[9, 8, 2, 3, 7, 5, 6, 1, 4, 10]
[3, 1, 5, 9, 10, 6, 2, 4, 8, 7]
[2, 4, 10, 9, 8, 1, 7, 6, 5, 3]
[4, 6, 3, 7, 8, 5, 10, 2, 1, 9]
[7, 6, 3, 9, 2, 1, 5, 4, 10, 8]
[6, 5, 10, 8, 3, 9, 7, 2, 1, 4]
[5, 7, 2, 9, 6, 8, 10, 1, 3, 4]
[3, 4, 8, 9, 1, 5, 2, 10, 7, 6]
[6, 1, 5, 2, 10, 9, 7, 4, 3, 8]
[3, 8, 9, 6, 4, 5, 10, 7, 2, 1]
[9, 4, 10, 5, 8, 7, 6, 2, 3, 1]
[4, 6, 5, 8, 10, 2, 1, 7, 9, 3]
[7, 6, 4, 8, 9, 5, 3, 2, 1, 10]
[7, 8, 3, 6, 9, 1, 5, 2, 10, 4]
[9, 10, 3, 8, 6, 1, 2, 7, 4, 5]
[10, 4, 9, 8, 3, 6, 2, 7, 5, 1]
[10, 7, 1, 5, 3, 2, 6, 9, 8, 4]
[3, 2, 8, 6, 4, 10, 9, 7, 5, 1]
[5, 6, 10, 1, 9, 4, 2, 7, 3, 8]
[8, 7, 5, 1, 3, 10, 4, 2, 9, 6]
[5, 8, 4, 1, 3, 10, 6, 2, 9, 7]
[8, 7, 2, 3, 1, 10, 6, 4, 5, 9]
[8, 2, 7, 10, 4, 3, 6, 1, 5, 9]
[1, 4, 5, 7, 8, 2, 9, 3, 6, 10]
[4, 8, 10, 7, 3, 1, 9, 6, 5, 2]
[9, 4, 10, 2, 3, 7, 8, 6, 1, 5]
[7, 4, 3, 6, 1, 8, 2, 9, 10, 5]
[6, 2, 9, 7, 10, 1, 4, 3, 5, 8]
[9, 4, 6, 7, 3, 1, 8, 5, 10, 2]
[8, 5

In [32]:
for count in range(data_len):
    sheet[chr(ord('A')+count)+'1'] = "第{}列".format(count+1)
#wb.save('test.xlsx')  

In [33]:
for i in json_music:
    #print(i['openNum'])
    sheet.append(i['openNum'])



In [35]:
filename = url.split('/')[-1].split('.')[0]
wb.save(filename+'.xlsx')

In [ ]:
def csv_output(file_name,list_data,col_name=''):
    with open(file_name,'w', newline = '',encoding = 'gb18030') as csvfile:
        writer=csv.writer(csvfile,dialect='excel')
        if col_name:
            writer.writerow([col_name[0],col_name[1],col_name[2],col_name[3],col_name[4]])
        for value in list_data:
            writer.writerow([value[0],value[1],value[2],value[3],value[4]])

In [3]:
def analysis(url):
    res = requests.get(url)
    # 返回一个response对象，赋值给res
    html = res.text
    print(res.status_code)
    soup = BeautifulSoup( html,'html.parser') 
    return soup 

In [4]:
bs = analysis(url)

200


In [9]:
print(bs)

[{"openDateTime":"2019-01-02 23:57:30","issue":"723663","openNum":[10,6,7,9,4,3,2,1,8,5],"sumArr":[16,2,1,0],"dtArr":[1,2,1,1,1],"formArr":[],"mimcryArr":[],"compareArr":[2,2,2,1,2,1,1,2,1,1],"sumType":null,"wuxing":null},{"openDateTime":"2019-01-02 23:52:30","issue":"723662","openNum":[1,9,4,5,2,7,3,6,10,8],"sumArr":[10,2,2,0],"dtArr":[2,2,2,1,2],"formArr":[],"mimcryArr":[],"compareArr":[1,1,2,1,1,2,2,2,1,2],"sumType":null,"wuxing":null},{"openDateTime":"2019-01-02 23:47:30","issue":"723661","openNum":[9,8,2,3,7,5,6,1,4,10],"sumArr":[17,1,1,0],"dtArr":[2,1,1,2,1],"formArr":[],"mimcryArr":[],"compareArr":[2,1,1,2,2,2,1,1,1,2],"sumType":null,"wuxing":null},{"openDateTime":"2019-01-02 23:42:30","issue":"723660","openNum":[3,1,5,9,10,6,2,4,8,7],"sumArr":[4,2,2,0],"dtArr":[2,2,1,1,1],"formArr":[],"mimcryArr":[],"compareArr":[1,2,1,2,1,2,2,2,1,1],"sumType":null,"wuxing":null},{"openDateTime":"2019-01-02 23:37:30","issue":"723659","openNum":[2,4,10,9,8,1,7,6,5,3],"sumArr":[6,2,2,0],"dtArr":[

In [ ]:
url = 'https://www.cp550.com/data/bjpk10/lotteryList/2019-01-02.json?KJXTURH3UD9JAVWD2RMH'

'2019-01-02'

In [4]:
import easygui as g
msg = "请输入URL地址"
title = "数据爬取"
url = g.enterbox(msg,title)  #设置显示内容、标题、输入下上界
print(url)
    

aaaaaaaaaaaaaaaaaa


In [5]:
print(type(url))

<class 'str'>


In [6]:
print([2,2] - [1,1])

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [9]:
import numpy as np
a = np.array([1,2,3])
print(a)
print(a - np.array([1,1,1]))

[1 2 3]
[0 1 2]


In [12]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
for month in range(5,6+1):
    for date in range()

In [1]:
url = 'https://www.cp550.com/data/bjpk10/lotteryList/{}.json?KJXTURH3UD9JAVWD2RMH'.format('2019-01-02')

In [2]:
print(url)

https://www.cp550.com/data/bjpk10/lotteryList/2019-01-02.json?KJXTURH3UD9JAVWD2RMH
