# 第四课 NumPy和SciPy
## 第六节 向量化及通用函数

In [16]:
import numpy as np

* 向量化

In [35]:
a = np.arange(100000, dtype=float)
b = np.arange(100000, 0, -1, dtype=float)

In [36]:
# 未使用向量化
import time

begin = time.time()
results = []
for i, j in zip(a, b):
    results.append(i * j)
end = time.time()
print('运行时间：', end - begin)

运行时间： 0.03424072265625


In [37]:
# 使用向量化
begin = time.time()
results = a * b
end = time.time()
print('运行时间：', end - begin)

运行时间： 0.001546621322631836


* 广播操作

In [39]:
np.arange(3) + 5

array([5, 6, 7])

In [40]:
np.ones((3, 3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [41]:
np.arange(3).reshape((3, 1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

* 通用函数

In [43]:
arr = np.random.randn(2,3)
print(arr)

[[-1.14243468  0.62343218  1.10789425]
 [ 0.14386543  0.90263521  1.19952443]]


In [44]:
print(np.ceil(arr))
print(np.floor(arr))
print(np.rint(arr))
print(np.isnan(arr))

[[-1.  1.  2.]
 [ 1.  1.  2.]]
[[-2.  0.  1.]
 [ 0.  0.  1.]]
[[-1.  1.  1.]
 [ 0.  1.  1.]]
[[False False False]
 [False False False]]


In [45]:
np.multiply(np.arange(3), 5)

array([ 0,  5, 10])

In [47]:
np.arange(3) * 5

array([ 0,  5, 10])

In [48]:
np.divide(np.arange(3), 5)

array([0. , 0.2, 0.4])

In [49]:
np.arange(3) / 5

array([0. , 0.2, 0.4])