# 第四课 NumPy和SciPy
## 第二节 多维数组

In [1]:
import numpy as np

* 通过序列型对象创建数组

ndim, shape和dtype属性

In [9]:
# 一维数组
l = [1, 2, 3, 4, 5, 6]
data = np.array(l)
print(data)

print('维度个数', data.ndim)
print('各维度大小: ', data.shape)
print('数据类型: ', data.dtype)

[1 2 3 4 5 6]
维度个数 1
各维度大小:  (6,)
数据类型:  int32


In [10]:
# 二维数组
l = [[1., 2., 3.], [4., 5., 6.]]
data = np.array(l)
print(data)

print('维度个数', data.ndim)
print('各维度大小: ', data.shape)
print('数据类型: ', data.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
维度个数 2
各维度大小:  (2, 3)
数据类型:  float64


In [11]:
# 三维数组
l = [
        [
            [1, 2], 
            [3, 4]
        ], 
        [
            [5, 6], 
            [7, 8]
        ]
]
data = np.array(l)
print(data)

print('维度个数', data.ndim)
print('各维度大小: ', data.shape)
print('数据类型: ', data.dtype)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
维度个数 3
各维度大小:  (2, 2, 2)
数据类型:  int32


* np.zeros(), np.ones(), np.random.rand()

In [17]:
# np.zeros()
zeros_arr = np.zeros((3, 4))

# np.ones()
ones_arr = np.ones((2, 3))

# np.random.rand()
# 注意传入的参数和之前的不同
rand_arr = np.random.rand(4, 5)

print(zeros_arr)
print()
print(ones_arr)
print()
print(rand_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[0.80487316 0.80746905 0.98224149 0.48833136 0.14757387]
 [0.5864833  0.20119618 0.73582423 0.03319791 0.96663399]
 [0.85930893 0.35363352 0.10805405 0.29540476 0.88695512]
 [0.82192915 0.18710546 0.31167142 0.47198184 0.14923801]]


* np.arange()

In [19]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


* reshape()

In [20]:
arr2 = arr.reshape((5, 2))
print(arr2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


* astype()

In [21]:
print(arr2.dtype)

int32


In [22]:
arr3 = arr2.astype(float)
print(arr3.dtype)

float64
