# 第四课 NumPy和SciPy
## 第四节 常用方法

In [2]:
import numpy as np

In [4]:
data = np.arange(10).reshape(5, 2)
print(data)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [6]:
print(np.mean(data))
print(np.mean(data, axis=0))
print(np.mean(data, axis=1))

4.5
[4. 5.]
[0.5 2.5 4.5 6.5 8.5]


In [7]:
print(np.sum(data))
print(np.sum(data, axis=0))
print(np.sum(data, axis=1))

45
[20 25]
[ 1  5  9 13 17]


In [8]:
print(np.max(data))
print(np.max(data, axis=0))
print(np.max(data, axis=1))

9
[8 9]
[1 3 5 7 9]


In [11]:
print(np.std(data))
print(np.var(data))

2.8722813232690143
8.25


In [13]:
print(np.argmax(data))
print(np.argmax(data, axis=0))
print(np.argmax(data, axis=1))

9
[4 4]
[1 1 1 1 1]


In [14]:
print(np.cumsum(data))
print(np.cumsum(data, axis=0))
print(np.cumsum(data, axis=1))

[ 0  1  3  6 10 15 21 28 36 45]
[[ 0  1]
 [ 2  4]
 [ 6  9]
 [12 16]
 [20 25]]
[[ 0  1]
 [ 2  5]
 [ 4  9]
 [ 6 13]
 [ 8 17]]


In [15]:
print(np.any(data > 5))

True


In [16]:
print(np.all(data > 5))

False


In [17]:
arr = np.array([[1, 2, 1], [2, 3, 4]])
print(arr)

[[1 2 1]
 [2 3 4]]


In [18]:
print(np.unique(arr))

[1 2 3 4]
