# 第四课 NumPy和SciPy
## 第三节 多维数组操作

In [2]:
import numpy as np

* 索引与切片

In [6]:
# 一维数组索引
l = [1, 2, 3, 4, 5, 6]
data = np.array(l)
print(data)

[1 2 3 4 5 6]


In [5]:
print(l[0])
print(l[-1])
print(l[3:])

1
6
[4, 5, 6]


In [8]:
# 多维数组索引
data = np.arange(9).reshape(3, 3)
print(data)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
print(data[:2, 1:])

[[1 2]
 [4 5]]


In [10]:
print(data[2])
print(data[2, :])
print(data[2:, :])

[6 7 8]
[6 7 8]
[[6 7 8]]


In [11]:
print(data[:, :2])

[[0 1]
 [3 4]
 [6 7]]


In [12]:
print(data[1, :2])
print(data[1:2, :2])

[3 4]
[[3 4]]


In [14]:
# 条件索引
# 找出数据中大于4的数据
is_gt = data > 4

In [15]:
print(is_gt)

[[False False False]
 [False False  True]
 [ True  True  True]]


In [16]:
print(data[is_gt])

[5 6 7 8]


In [17]:
# 简写
print(data[data > 4])

[5 6 7 8]


In [18]:
# 找出数据中大于4的偶数
print(data[ (data > 4) & (data % 2 == 0)])

[6 8]


* 转置

In [19]:
data = np.arange(15).reshape(3, 5)
print(data)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [22]:
print(data.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [23]:
print(np.transpose(data))

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [24]:
print(np.swapaxes(data, 0, 1))

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
